name: 'claims_data_model'
version: '1.0.0'
config-version: 2

profile: 'default'



dispatch:
  - macro_namespace: dbt
    search_order: [ 'the_tuva_project', 'dbt']

model-paths: ["models"]
analysis-paths: ["../analyses"]
test-paths: ["../tests"]
seed-paths: ["../seeds"]
macro-paths: ["../macros"]
snapshot-paths: ["../snapshots"]
docs-paths: ["docs"]

target-path: "../target"
log-path: "../logs"
packages-install-path: "../dbt_packages"
clean-targets:
  - "../target"
  - "../dbt_packages"

models:
  claims_data_model:
    +materialized: view
    +docs:
      node_color: "#1a0707"
  claims_preprocessing:
    +docs:
      node_color: "#0f3d0b"
    staging:
      +docs:
        show: false
    intermediate:
      +docs:
        show: false
  cms_chronic_conditions:
    +docs:
      node_color: "#2e0e0e"
    staging:
      +docs:
        show: false
  data_profiling:
    +docs:
      node_color: "#141161"
    staging:
      +docs:
        show: false
  pmpm:
    +docs:
      node_color: "#abab26"
    intermediate:
      +docs:
        show: false
  readmissions:
    +docs:
      node_color: "#161a7d"
    staging:
      +docs:
        show: false
    intermediate:
      +docs:
        show: false
  tuva_chronic_conditions:
    +docs:
      node_color: "#804912"


seeds:
  data_profiling:
    +docs:
      node_color: "#141161"
  terminology:
    +docs:
      node_color: "#460d4f"
  tuva_chronic_conditions:
    +docs:
      node_color: "#804912"

snapshots:
  data_profiling:
    +docs:
      show: false